name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: ./contact-impl/appops-dev
      run: docker-compose up --build -d
      
    - name: Build the application Docker image
      working-directory: ./contact-impl
      run: |
            docker build . --file Dockerfile --tag contact:$(date +%s)
           
