name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build push the Docker image
      working-directory: ./contact-impl
      run: |
          echo ${{ secrets.DOCKER_PASSWORD}} |sudo docker login ghcr.io -u aino-rtejas --password-stdin
          docker build . --file Dockerfile --tag ghcr.io/aino-rtejas/contact:latest
          docker images
          docker push ghcr.io/aino-rtejas/contact-latest
