name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build push the Docker image
      working-directory: ./contact-impl/appops-dev
      run: |
          echo ${{ secrets.DOCKER_PASSWORD}} |sudo docker login ghcr.io -u aino-rtejas --password-stdin
          docker-compose up --build -d
          docker images
          docker push appops-dev_apache2
